source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'letter_opener_web'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'capistrano', '3.6.0'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano3-unicorn'
end
gem 'twitter-bootstrap-rails'
gem 'devise'
gem 'rails_12factor', group: :production
gem 'rails_admin'
gem 'cancan'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'carrierwave'
gem 'rmagick'
gem 'fog'
gem 'pusher'
gem 'faker'
gem 'kaminari'
gem 'dotenv-rails'
gem 'unicorn'
gem 'therubyracer', platforms: :ruby
